master:
  image: redis:3
  ports:
    - "0.0.0.0:3331:6379"
slave:
  image: redis:3
  command: redis-server --slaveof redis-master 6379
  links:
    - master:redis-master
  ports:
    - "0.0.0.0:3332:6379"
sentinel:
  build: sentinel
  environment:
    - SENTINEL_DOWN_AFTER=5000
    - SENTINEL_FAILOVER=5000    
  links:
    - master:redis-master
    - slave
  ports:
    - "0.0.0.0:3333:6379"
    - "0.0.0.0:26379:26379"
