mongo:
  image: mongo
  restart: always
  volumes:
    - /data/mongodb:/data/db
  ports:
    - 0.0.0.0:27017:27017
  environment:
    MONGO_INITDB_ROOT_USERNAME: root
    MONGO_INITDB_ROOT_PASSWORD: password

